spring:
  datasource:
    url: jdbc:mysql://106.13.122.154:3306/jdy?characterEncoding=utf8&useSSL=false&serverTimezone=UTC
    username: root
    password: Jindan.root
    hikari:
      connection-timeout: 50000
      min-idle: 10
      max-pool-size: 20
      connection-test-query: SELECT 1
      validation-timeout: 250

server:
  port: 8081
  connection-timeout: 5000ms
  tomcat:
    uri-encoding: UTF-8
    max-threads: 1000
    min-spare-threads: 30
  servlet:
    context-path: /jdy-admin
    session:
      cookie:
        http-only: true

mybatis-plus:
  mapper-locations: classpath:/com/jiandan/jdy/common/mapper/*Mapper.xml
  typeAliasesPackage: com.jiandan.jdy.common.pojo
  configuration:
    map-underscore-to-camel-case: true
    call-setters-on-nulls: true
    cache-enabled: false
  global-config:
    banner: false
    db-config:
      db-type: mysql