spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/jdy?characterEncoding=utf8&useSSL=false&serverTimezone=UTC
    username: root
    password: 2021413
    hikari:
      connection-timeout: 50000
      min-idle: 10
      max-pool-size: 20
      connection-test-query: SELECT 1
      validation-timeout: 250
  redis:
      host: 60.205.218.186
      port: 6379
      timeout: 5000ms
      lettuce:
        pool:
          max-active: 100
          max-wait: 15000ms
          min-idle: 5

server:
  port: 20201
  connection-timeout: 5000ms
  tomcat:
    uri-encoding: UTF-8
    max-threads: 1000
    min-spare-threads: 30
  servlet:
    context-path: /jdy-admin
    session:
      cookie:
        http-only: true

mybatis-plus:
  mapper-locations: classpath:/com/jiandan/jdy/mapper/*.xml
  typeAliasesPackage: com.jindan.jdy.common
  configuration:
    map-underscore-to-camel-case: true
    call-setters-on-nulls: true
    cache-enabled: false
  global-config:
    banner: false
    db-config:
      db-type: mysql
pagehelper:
  reasonable: false # 禁用合理化时，如果pageNum<1或pageNum>pages会返回空数据 #    address: 106.13.122.154:2181      #    address: 127.0.0.1:2181
  support-methods-arguments: true
  params: count=countSql
  row-bounds-with-count: true
  helper-dialect: mysql