spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/jdy?characterEncoding=utf8&useSSL=false&serverTimezone=CTT
    username: root
    password: 2021413
    hikari:
      connection-timeout: 50000
      min-idle: 10
      max-pool-size: 20
      connection-test-query: SELECT 1
      validation-timeout: 250
  redis:
      host: 60.205.218.186
      port: 6379
      timeout: 5000ms
      lettuce:
        pool:
          max-active: 100
          max-wait: 15000ms
          min-idle: 5
      password: hnjindan
  messages:
    encoding: UTF-8
    basename: i18n/messages
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
      enabled: true

server:
  port: 20201
  connection-timeout: 5000ms
  tomcat:
    uri-encoding: UTF-8
    max-threads: 1000
    min-spare-threads: 30
  servlet:
    context-path: /jdy-admin
    session:
      cookie:
        http-only: true

mybatis-plus:
  mapper-locations: classpath:/com/jiandan/jdy/mapper/*.xml
  typeAliasesPackage: com.jindan.jdy.common
  configuration:
    map-underscore-to-camel-case: true
    call-setters-on-nulls: true
    cache-enabled: false
  global-config:
    banner: false
    db-config:
      db-type: mysql
pagehelper:
  reasonable: false # 禁用合理化时，如果pageNum<1或pageNum>pages会返回空数据 #    address: 106.13.122.154:2181      #    address: 127.0.0.1:2181
  support-methods-arguments: true
  params: count=countSql
  row-bounds-with-count: true
  helper-dialect: mysql

aliyun:
  oss:
    file:
      endpoint: oss-cn-beijing.aliyuncs.com
      keyid: LTAI4FpooemptjwNoXAKe4Su
      keysecret: Wt8tkmUfjGiOp9NhJ8C4fqbbMDDVpb
      bucketname: kong15
      filehost: avatar
      host: career
apppush:
  appId: 123456
  appKey: 7899+456
  masterSecret: 123585555
  url: http://sdk.open.api.igexin.com/apiex.htm
wechat:
  mpAppId: wxb5b6dfa9e8b12f50
  mpAppSecret: 6da768a60cdd737cc30c32134d7071c6
  token: 33333
  aeskey: 44444
